"""empty message

Revision ID: fd6d90982b9c
Revises: aba69ec1e3da
Create Date: 2024-10-27 15:52:44.965294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6d90982b9c'
down_revision: Union[str, None] = 'aba69ec1e3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'developers', ['id'])
    op.add_column('projects', sa.Column('developer_count', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'projects', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'developer_count')
    op.drop_constraint(None, 'developers', type_='unique')
    # ### end Alembic commands ###
